version: "3.3"
services:
  octave-container:
    image: gnuoctave/octave:8.2.0
    container_name: "octave-container"
    working_dir: /mnt
    volumes:
      - ./solution:/mnt
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
